# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('method', models.CharField(default='GET', max_length=16)),
                ('encoding', models.CharField(default='', max_length=16)),
                ('priority', models.IntegerField(default=0)),
                ('dont_filter', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_data', models.CharField(default='', max_length=64)),
                ('cookie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.Config')),
            ],
        ),
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_data', models.CharField(default='', max_length=64)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.Config')),
            ],
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.CharField(default='', max_length=64)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.Config')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('accept', models.CharField(default='application/json, text/javascript, */*', max_length=64)),
                ('accept_encoding', models.CharField(default='gzip, deflate, br', max_length=64)),
                ('accept_language', models.CharField(default='en-US,en;q=0.8,nl;q=0.6', max_length=64)),
                ('connection', models.CharField(default='keep-alive', max_length=64)),
                ('content_length', models.IntegerField(default=224)),
                ('content_type', models.CharField(default='application/x-www-form-urlencoded', max_length=64)),
                ('host', models.CharField(default='/', max_length=200)),
                ('origin', models.CharField(default='/', max_length=200)),
                ('referer', models.CharField(default='/', max_length=200)),
                ('user_agent', models.CharField(default='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36', max_length=200)),
                ('x_Requested_with', models.CharField(default='XMLHttpRequest', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_data', models.CharField(default='', max_length=64)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.Config')),
            ],
        ),
        migrations.CreateModel(
            name='Selector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(default='', max_length=200)),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.Config')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=200)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.Config')),
            ],
        ),
        migrations.AddField(
            model_name='config',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.Header'),
        ),
    ]
