# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_auto_20171029_1307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flags',
            new_name='Flag',
        ),
    ]
