# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_auto_20171029_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='selector',
            name='selector',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='collect.Config'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='selector',
            name='expression',
            field=models.CharField(default='', max_length=200),
        ),
    ]
