# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=64)),
                ('executed', models.BooleanField(default=0)),
                ('created', models.DateField()),
                ('archived', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ActionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.Action')),
            ],
        ),
    ]
