# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='archived',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
