# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20170626_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='executed',
            new_name='completed',
        ),
    ]
