# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_auto_20170627_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='filed',
        ),
        migrations.AddField(
            model_name='action',
            name='completed',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='action',
            name='filed',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo_list.Action'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detail',
            name='explanation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
