# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0007_auto_20170627_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='completed',
        ),
        migrations.AddField(
            model_name='action',
            name='completed',
            field=models.BooleanField(default=0),
        ),
    ]
